# Generated by Django 4.2.4 on 2023-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='reject_reason',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
