# Generated by Django 4.2.4 on 2023-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_blooddonate_reject_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonate',
        ),
    ]
