# Generated by Django 4.2.4 on 2023-09-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bbm_blood_group',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(default=0)),
                ('blood_group', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='blood.bloodgroup')),
            ],
            options={
                'db_table': 'bbm_stock',
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.PositiveIntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blood.bloodgroup')),
            ],
            options={
                'db_table': 'bbm_blood_request',
            },
        ),
    ]
