# Generated by Django 4.2.4 on 2023-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='blood_group',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
