# Generated by Django 4.2.4 on 2023-10-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_bloodgroup_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='reject_reason',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
