# Generated by Django 4.2.4 on 2023-10-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_delete_blooddonate'),
        ('blood', '0004_bloodrequest_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('added', models.DateTimeField()),
            ],
            options={
                'db_table': 'bbm_branch',
            },
        ),
        migrations.CreateModel(
            name='BloodDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='Nothing', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('reject_reason', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Rejected')], default=2)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blood.bloodgroup')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
            options={
                'db_table': 'bbm_blood_donate',
            },
        ),
    ]
