# Generated by Django 4.2.4 on 2023-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_branch_blooddonate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
