# Generated by Django 4.2.4 on 2023-10-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_alter_branch_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='donate_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blood.branch'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blood.branch'),
        ),
    ]
