# Generated by Django 4.2.4 on 2023-10-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_blooddonate_donate_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='donate_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blood.branch'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blood.branch'),
        ),
    ]
