# Generated by Django 4.2.4 on 2023-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
