# Generated by Django 4.2.4 on 2023-10-10 13:18

import auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'USER_ALREADY_PRESENT'}, max_length=150, unique=True, validators=[auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
