# Generated by Django 4.2.4 on 2023-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
